import argparse
parser = argparse.ArgumentParser()

parser.add_argument('--epoch', type=int, default=80, help='epoch number')
parser.add_argument('--lr', type=float, default=1e-4, help='learning rate')
parser.add_argument('--batchsize', type=int, default=8, help='training batch size')
parser.add_argument('--trainsize', type=int, default=352, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.3, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=20, help='every n epochs decay learning rate')
parser.add_argument('--weight_decay', type=float, default=1e-4, help='weight decay')
parser.add_argument('--load', type=str, default=None, help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='1', help='train use gpu')
parser.add_argument('--rgb_root', type=str, default='E://Newfolder//Exp//ors-4199//Train//', help='the training rgb images root')
parser.add_argument('--gt_root', type=str, default='E://Newfolder//Exp//ors-4199//GT//Train//', help='the training gt images root')
parser.add_argument('--test_rgb_root', type=str, default='E://Newfolder//Exp//ors-4199//Test//', help='the test rgb images root')
parser.add_argument('--test_gt_root', type=str, default='E://Newfolder//Exp//ors-4199//GT//Test//', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='384', help='the path to save models and logs')
opt = parser.parse_args()